### ISSUE TITLE
Module exports expressiveness

### ISSUE THREAD

**Issue by j3k0** [j3k0/ganomede-boilerplate#12]
@elmigranto I just have a general remark about a design style...Take this as a small complain from your usual peer-reviewer :-), no more than that.

 It happens that it applies to the router.* modules among others.  See below 

```js
// from https://github.com/j3k0/ganomede-usermeta/blob/master/tests/usermeta.router.test.js#L8-L29
const usermetaRouter = require('../src/usermeta.router');
const usermeta = usermetaRouter({...});
usermeta('', server);

// from https://github.com/j3k0/ganomede-usermeta/blob/master/tests/about.router.test.js#L13
const about = require('../src/about.router');
about(config.http.prefix, server);
```

For those modules that just return an anonymous function, it's generally hard to know what it does unless I open the file to check out (or get used to the convention in use, when they're consistent). In both cases, it's harder that reading a clear function name. When different similar modules (like routers, for instance) expose methods that don't do the same thing, it gets harder...

Generally, functions that do stuff are easier to understand with verbs like `createSomething`, `loadSomething`, `addStuff`, ... Methods called `something()` require more thinking to figure out. _Some exceptions: getters, like `users.byName(...)`, conversions like `something(stuff)` (which are variants of constructor functions). Anyway, I diverge._

It would be more explicit with named function like that:
```js
const {createRouter} = require('../src/usermeta.router');
const {addRoutes} = createRouter({...});
addRoutes('', server);
```

For `*.router.js` that return an `addRoutes`, it would look like this:

```js
const {addRoutes} = require('../src/usermeta.router');
addRoutes('', server);
```

If not consistent, at least it's more expressive.

When exporting a anonymous method, I think module should be named after what the method does.

```js
const addUsermetaRoutes = require('./add-usermeta-routes');
```

"tastes" weird but at least it is expressive.

🔥 Burn after reading

**Comment by elmigranto** [comment]
Ahh, naming things :)

I agree. Used to express' style, didn't really noticed how confusing it looks when that terminology moved to restify without using same mounting technique…

``` js
const app = express();
const UsermetaRouter = require('./UsermetaRouter');

app.use(`/usermeta/v1`, new UsermetaRouter(options));
```
