### ISSUE TITLE
Logging errors

### ISSUE THREAD

**Issue by elmigranto** [j3k0/ganomede-boilerplate#13]
Bunyan object inspection stops at some depth resulting in stuff like this (see `body.errors`).

![screenshot 2017-03-16 21 10 39](https://cloud.githubusercontent.com/assets/886388/24006246/0d27c274-0a8d-11e7-8c13-90414177f687.png)

We can use our `utils.debugInspect` as serializer for `err` or `error` props (plays fine with circular objects, and hopefuly we don't log megabytes of response body as `err`, but can add `instanceof` check for `Error`):

``` js
// create logger
module.exports = bunyan.createLogger({
  level: config.logLevel,
  name: config.name,
  serializers: {
    err: debugInspect,
    error: debugInspect
  }
});

// arg order is wierd, but w/ever
logger.error({err}, 'some kind of message about how we got here')
```
![screenshot 2017-03-16 21 15 40](https://cloud.githubusercontent.com/assets/886388/24006471/b87794e2-0a8d-11e7-8fb9-eeb2ec215e18.png)

**Comment by elmigranto** [comment]
I don't get it 😡 now it's suddenly fine with no serializers, computers…
![screenshot 2017-03-16 21 18 41](https://cloud.githubusercontent.com/assets/886388/24006612/253a335a-0a8e-11e7-9be0-ae4a4b73e976.png)

**Comment by elmigranto** [comment]
Okay.

``` js
// Doesn't work:
logger.error(err);
logger.error(err, 'bad logger');

// Kinda works
logger.error({err});

// Works
logger.error({err}, 'good logger');
```

Guess we can detect `logger.error(err)` situation… Or we can go over all the repos and change all invokations it to at least "kinda works" status.

**Comment by elmigranto** [comment]
For some reason, `restify.RestError` gets printed by bunyan as `{}`. Gotta go with `debugInspect` looks like.

**Comment by elmigranto** [comment]
I'm wondering if it's better to dump logs to `stderr` and not `stdout`. Matters most in scripts that output stuff like CSV. Worth noting that all severity levels go to `stdout` atm.

**Comment by j3k0** [comment]
Better to log to `stdout` in the general case. Conversion scripts that needs a clean `stdout` output can change the bunyan output stream to log to `stderr` but I'd rather not have this be the default (just not to make things more complex -- and broken -- in the current deployments)
